purge:
  trigger: space
  max_backups_count: 25
  max_backups_space: 5
  max_backups_time: 365
profiles:
  -
    name: Backup
    root: /backup
    exclude_paths: null
    exclude_files: null
    schedule: true
    schedule_at: '* 2 * * 7'
