title: 'NIEwolnicy Systemu'
default_lang: PL
author:
  name: 'Gabriel Schmidt-Jensen'
  email: niewolnicysystemu@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Oficjalna strona zespołu - "NIEwolnicy Systemu" Informacje o zespole, kontakt, zdjęcią, filmy i więcej'
  'Zespół zduńska wola': 'Oficjalna strona zespołu - "NIEwolnicy Systemu" Informacje o zespole, kontakt, zdjęcią, filmy i więcej'
  'Polskie zespoły': 'Oficjalna strona zespołu - "NIEwolnicy Systemu" Informacje o zespole, kontakt, zdjęcią, filmy i więcej'
  'NIEwolnicy Systemu': 'Oficjalna strona zespołu - "NIEwolnicy Systemu" Informacje o zespole, kontakt, zdjęcią, filmy i więcej'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
