enabled: true
production-mode: true
grid-size: grid-xl
header-fixed: true
header-animated: true
header-dark: true
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo:
  user/themes/darkquark/images/logo/cmyk_ns_poziome-biale-bez_tla.png:
    name: cmyk_ns_poziome-biale-bez_tla.png
    full_path: cmyk_ns_poziome-biale-bez_tla.png
    type: image/png
    size: 23320
    path: user/themes/darkquark/images/logo/cmyk_ns_poziome-biale-bez_tla.png
custom_logo_mobile:
  user/themes/darkquark/images/logo/cmyk_ns_poziome-biale-bez_tla.png:
    name: cmyk_ns_poziome-biale-bez_tla.png
    full_path: cmyk_ns_poziome-biale-bez_tla.png
    type: image/png
    size: 23320
    path: user/themes/darkquark/images/logo/cmyk_ns_poziome-biale-bez_tla.png
